# @file
# .travis.yml - Drupal driver for Doctrine DBAL.

language: php

sudo: false

php:
  - 7
  #- nightly

branches:
  except:
    - /^dev-.*/

env:
  matrix:
    - DB_DR="pdo_mysql" DB_DB="drudbal"
    - DB_DR="mysqli"    DB_DB="drudbal"
  global:
    - DRUPAL_PATH="$HOME/drupal8"
    - PATH="$PATH:$DRUPAL_PATH/vendor/bin:$HOME/.composer/vendor/bin"
    # Installation variables.
    - DRUPAL_DATABASE_NAME="$DB_DB"
    - DRUPAL_SERVER_ADDRESS="127.0.0.1"
    - DRUPAL_SERVER_HTTP_PORT="8080"
    - DBAL_URL="$DB_DR://root:@$DRUPAL_SERVER_ADDRESS/$DRUPAL_DATABASE_NAME"
    # Drupal PHPUnit test variables.
    - SIMPLETEST_DB="dbal://root:@$DRUPAL_SERVER_ADDRESS/$DRUPAL_DATABASE_NAME?namespace=Drupal%5CDriver%5CDatabase%5Cdbal&dbal_driver=$DB_DR#drudbal_"
    - SIMPLETEST_BASE_URL="http://$DRUPAL_SERVER_ADDRESS:$DRUPAL_SERVER_HTTP_PORT"

mysql:
  database: $DB_DB
  username: root
  encoding: utf8

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  # Remove XDebug
  - phpenv config-rm xdebug.ini
  # Add APCu extension.
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Get Drupal core and dependencies
  - git clone http://git.drupal.org/project/drupal.git $DRUPAL_PATH
  - cd $DRUPAL_PATH
  - composer install

  # Apply Drupal core patches
  # [#2605284] Testing framework does not work with contributed database drivers
  - curl https://www.drupal.org/files/issues/simpletest_is_broken_on-2605284-89.patch | git apply
  # [#2867700] ConnectionUnitTest::testConnectionOpen fails if the driver is not implementing a PDO connection
  - curl https://www.drupal.org/files/issues/2867700-2.patch | git apply
  # [#2867788] Log::findCaller fails to report the correct caller function with non-core drivers.
  - curl https://www.drupal.org/files/issues/2867788-12.patch | git apply
  # [#2871374] SelectTest::testVulnerableComment fails when driver overrides Select::__toString
  - curl https://www.drupal.org/files/issues/2871374-2.patch | git apply

  # Get Drupal Console
  - composer require "drupal/console:~1.0" --prefer-dist --optimize-autoloader

  # Get Doctrine DBAL
  - composer require "doctrine/dbal:^2.5.12"

install:
  # Copy the repo to the modules/contrib directory.
  - mkdir -p $HOME/drupal8/modules/contrib/drudbal
  - cp -r $HOME/build/mondrake/drudbal $HOME/drupal8/modules/contrib

  # Create a directory for the driver, and symlink it to the module's one.
  - mkdir -p $HOME/drupal8/drivers/lib/Drupal/Driver/Database/
  - cd $HOME/drupal8/drivers/lib/Drupal/Driver/Database/
  - ln -s $HOME/drupal8/modules/contrib/drudbal/drivers/lib/Drupal/Driver/Database/dbal dbal

  # Install Drupal
  - cd $HOME/drupal8/core
  - cp $HOME/drupal8/modules/contrib/drudbal/misc/install_cli.php install_cli.php
  - php install_cli.php

  # Get a webserver running.
  #- drupal --quiet server "$DRUPAL_SERVER_ADDRESS:$DRUPAL_SERVER_HTTP_PORT" &
  #- sleep 4s
  - drupal site:status

script:
  - cd $HOME/drupal8/core
  # Only run selected tests to avoid Travis timeout.
  - phpunit --testsuite unit --group Database,Cache,Entity --verbose
  - phpunit --testsuite kernel --group Database,Cache --verbose
  - phpunit tests/Drupal/KernelTests/Core/Entity/ConfigEntityQueryTest.php
  - phpunit tests/Drupal/KernelTests/Core/Entity/EntityQueryTest.php
  - phpunit tests/Drupal/KernelTests/Core/Entity/EntityQueryAggregateTest.php
  - phpunit tests/Drupal/KernelTests/Core/Entity/EntityQueryRelationshipTest.php
  - phpunit tests/Drupal/KernelTests/Core/Entity/FieldSqlStorageTest.php
  - phpunit tests/Drupal/KernelTests/Core/Entity/FieldTranslationSqlStorageTest.php

notifications:
  email: false
