# @file
# .travis.yml - Drupal driver for Doctrine DBAL.

os: linux

language: php

dist: bionic

php: 7.4

branches:
  except:
    - /^dev-.*/

jobs:
  include:
#    - env: DRUDBAL_ENV="mysql" TEST_ARGS="--group Database"
#      services:
#        - mysql
#    - env: DRUDBAL_ENV="dbal/mariadb" TEST_ARGS="--group Database"
#      addons:
#        mariadb: '10.2'
#    - env: DRUDBAL_ENV="dbal/mysql" TEST_ARGS="--group Database"
#      services:
#        - mysql
    - env: DRUDBAL_ENV="dbal/mysql" TEST_ARGS="--group Database,Entity,Field"
      services:
        - mysql
#    - env: DRUDBAL_ENV="dbal/mysql" TEST_ARGS="--group Installer,Cache,Config"
#      services:
#        - mysql
#    - env: DRUDBAL_ENV="dbal/mysql" TEST_ARGS="--group field"
#      services:
#        - mysql
#    - env: DRUDBAL_ENV="dbal/mysql" TEST_ARGS="--group file"
#      services:
#        - mysql
#    - env: DRUDBAL_ENV="dbal/mysql" TEST_ARGS="--group views"
#      services:
#        - mysql
#    - env: DRUDBAL_ENV="dbal/mysqli" TEST_ARGS="--group Database,Entity,Field"
#      services:
#        - mysql
#    - env: DRUDBAL_ENV="dbal/mysqli" TEST_ARGS="--group Installer,Cache,Config"
#      services:
#        - mysql
#    - env: DRUDBAL_ENV="dbal/mysqli" TEST_ARGS="--group field"
#      services:
#        - mysql
#    - env: DRUDBAL_ENV="dbal/mysqli" TEST_ARGS="--group file"
#      services:
#        - mysql
#    - env: DRUDBAL_ENV="dbal/mysqli" TEST_ARGS="--group views --testsuite=kernel"
#      services:
#        - mysql
#    - env: DRUDBAL_ENV="dbal/mysqli" TEST_ARGS="--group views --testsuite=functional"
#      services:
#        - mysql
#    - env: DRUDBAL_ENV="dbal/mysqli" TEST_ARGS="--group Database,Entity,Field"
#      services:
#        - mysql
#    - env: DRUDBAL_ENV="sqlite" TEST_ARGS="--group Database"
    - env: DRUDBAL_ENV="dbal/sqlite/file" TEST_ARGS="--group Database,Entity,Field"
    #- env: DRUDBAL_ENV="dbal/sqlite/file" TEST_ARGS="--group Database"
    #- env: DRUDBAL_ENV="dbal/sqlite/file" TEST_ARGS="tests/Drupal/KernelTests/Core/Database/RegressionTest.php"
#    - env: DRUDBAL_ENV="dbal/sqlite/file" TEST_ARGS="tests/Drupal/KernelTests/Core/Database/SchemaTest.php"
#    - env: DRUDBAL_ENV="dbal/sqlite/file" TEST_ARGS="--group Installer,Cache,Config"
#    - env: DRUDBAL_ENV="dbal/sqlite/file" TEST_ARGS="--group field"
#    - env: DRUDBAL_ENV="dbal/sqlite/file" TEST_ARGS="--group views"
#    - stage: Allow Failures
#      env: DRUDBAL_ENV="dbal/sqlite/file" TEST_ARGS="--group file"
#    - stage: Allow Failures
#      env: DRUDBAL_ENV="dbal/sqlite/memory" TEST_ARGS="--group Database,Installer,Cache,Config,Entity,Field"
  fast_finish: true
#  allow_failures:
#    - env: DRUDBAL_ENV="dbal/sqlite/file" TEST_ARGS="--group file"
#    - env: DRUDBAL_ENV="dbal/sqlite/memory" TEST_ARGS="--group Database,Installer,Cache,Config,Entity,Field"

cache:
  directories:
    - $HOME/drupal_staging
    #- $ORACLE_DOWNLOAD_DIR
    - $HOME/.composer/cache

before_install:
  # Set variables.

  # Drupal paths.
  - export DRUPAL_STAGING_DIR="$HOME/drupal_staging"
  - export DRUPAL_PATH="$HOME/drupal8"
  - export PATH="$PATH:$DRUPAL_PATH/vendor/bin:$HOME/.composer/vendor/bin"
  # Installation variables.
  - export HOST_ADDR="127.0.0.1"
  - export HTTP_PORT="8080"
  # Drupal PHPUnit test variables.
  - export SIMPLETEST_BASE_URL="http://$HOST_ADDR:$HTTP_PORT"
  # Suppress deprecation handling.
  #- export SYMFONY_DEPRECATIONS_HELPER=disabled

  # Expand environment-dependent variables.
  - |
      if [[ "$DRUDBAL_ENV" == "mysql" ]]; then
        export SIMPLETEST_DB="mysql://root:@$HOST_ADDR/drudbal#drudbal_"
        export INSTALL_VIA="drush"

      elif [[ "$DRUDBAL_ENV" == "dbal/mysql" ]]; then
        export DBAL_URL="mysql://root:@$HOST_ADDR/drudbal"
        export SIMPLETEST_DB="dbal://root:@$HOST_ADDR/drudbal?dbal_driver=pdo_mysql"
        export INSTALL_VIA="dbal"

      elif [[ "$DRUDBAL_ENV" == "dbal/mariadb" ]]; then
        export DBAL_URL="mysql://root:@$HOST_ADDR/drudbal"
        export SIMPLETEST_DB="dbal://root:@$HOST_ADDR/drudbal?dbal_driver=pdo_mysql"
        export INSTALL_VIA="dbal"

      elif [[ "$DRUDBAL_ENV" == "dbal/mysqli" ]]; then
        export DBAL_URL="mysqli://root:@$HOST_ADDR/drudbal"
        export SIMPLETEST_DB="dbal://root:@$HOST_ADDR/drudbal?dbal_driver=mysqli"
        export INSTALL_VIA="dbal"

      elif [[ "$DRUDBAL_ENV" == "sqlite" ]]; then
        export SIMPLETEST_DB="sqlite://localhost/sites/default/files/.ht.sqlite"
        export INSTALL_VIA="drush"
        export SQLITE_UPDATE="true"

      elif [[ "$DRUDBAL_ENV" == "dbal/sqlite/file" ]]; then
        export DBAL_URL="sqlite:///$DRUPAL_PATH/sqlite-drudbal"
        export SIMPLETEST_DB="dbal://localhost/$DRUPAL_PATH/sqlite-drudbal?dbal_driver=pdo_sqlite"
        export INSTALL_VIA="dbal"
        export SQLITE_UPDATE="true"

      elif [[ "$DRUDBAL_ENV" == "dbal/sqlite/memory" ]]; then
        export DBAL_URL="sqlite:///:memory:"
        export SIMPLETEST_DB="dbal://localhost/:memory:?dbal_driver=pdo_sqlite"
        export INSTALL_VIA="dbal"
        export SQLITE_UPDATE="true"

      elif [[ "$DRUDBAL_ENV" == "dbal/oci8" ]]; then
        export DBAL_URL="oci8://ORAROOT:DRUDBAL@$HOST_ADDR:1521/XE"
        export SIMPLETEST_DB="dbal://ORAROOT:DRUDBAL@$HOST_ADDR:1521/XE?dbal_driver=oci8"
        export INSTALL_VIA="dbal"

      fi

  # Update SQLite.
  - |
      if [[ "$SQLITE_UPDATE" == "true" ]]; then
        sudo echo "deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse" > /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get -y install sqlite3/focal
      fi

  # Remove XDebug.
  - phpenv config-rm xdebug.ini || true
  # Add APCu extension.
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Create the test db.
  - mysql -e 'CREATE DATABASE IF NOT EXISTS drudbal;' || true

  # Stage Drupal core to get dependencies.
  - |
      if [[ ! -f $DRUPAL_STAGING_DIR/index.php ]]; then
        git clone --depth=5 --branch=9.0.x http://git.drupal.org/project/drupal.git $DRUPAL_STAGING_DIR
        cd $DRUPAL_STAGING_DIR
        composer install --no-progress --no-suggest
        # Get Drush and Doctrine DBAL
        composer require drush/drush "mondrake/drudbal:dev-master" --no-progress --no-suggest
      fi

  # Copy staged Drupal core to running path.
  - mkdir -p $DRUPAL_PATH
  - cp -r $DRUPAL_STAGING_DIR/. $DRUPAL_PATH
  - cd $DRUPAL_PATH

  # Apply Drupal core patches.
  # [#2657888] Add Date function support in DTBNG
  - curl https://www.drupal.org/files/issues/2657888-18.patch | git apply
  # [#2992274] Installer tests fail if contrib driver hides database credentials form fields
  - curl https://www.drupal.org/files/issues/2019-04-02/2992274-5.patch | git apply

install:
  # Copy the cloned repo to the libraries/drudbal directory, overriding the
  # composer install.
  - rm -rf $DRUPAL_PATH/libraries/drudbal
  - cp -r $HOME/build/mondrake/drudbal $DRUPAL_PATH/libraries/drudbal

  # Create a directory for the driver, and symlink it to the module's one.
  - mkdir -p $DRUPAL_PATH/drivers/lib/Drupal/Driver/Database/
  - cd $DRUPAL_PATH/drivers/lib/Drupal/Driver/Database/
  - ln -s $DRUPAL_PATH/libraries/drudbal/lib dbal

  # Patch tests for debugging if necessary.
  - cd $DRUPAL_PATH
  - if [[ -f $DRUPAL_PATH/libraries/drudbal/tests/travis_ci/$DRUDBAL_ENV/test_debug.patch ]]; then git apply -v $DRUPAL_PATH/libraries/drudbal/tests/travis_ci/$DRUDBAL_ENV/test_debug.patch; fi

  # Install Drupal.
  - cd $DRUPAL_PATH/core
  - |
      if [[ "$INSTALL_VIA" == "drush" ]]; then
        drush site-install standard --db-url=$SIMPLETEST_DB -y
      elif [[ "$INSTALL_VIA" == "dbal" ]]; then
        cp $DRUPAL_PATH/libraries/drudbal/tests/travis_ci/install_cli.php install_cli.php
        php install_cli.php
      fi

  # Get a webserver running.
  - drush runserver $HOST_ADDR:$HTTP_PORT &
  - sleep 2s

  # Post install tasks.
  - drush core:status || true

script:
  # Only run selected tests to avoid Travis timeout.
  - $DRUPAL_PATH/vendor/bin/phpunit $TEST_ARGS

#after_script:
#  - cd $DRUPAL_PATH/libraries/drudbal
#  - $DRUPAL_PATH/vendor/bin/phpcs

notifications:
  email:
    on_success: never
    on_failure: never
