# @file
# .travis.yml - Drupal driver for Doctrine DBAL.

language: php

sudo: required

dist: precise

php:
  - 7.1
  #- nightly

branches:
  except:
    - /^dev-.*/

env:
  global:
    # Drupal paths.
    - DRUPAL_STAGING_DIR="$HOME/drupal_staging"
    - DRUPAL_PATH="$HOME/drupal8"
    - PATH="$PATH:$DRUPAL_PATH/vendor/bin:$HOME/.composer/vendor/bin"
    # Installation variables.
    - HOST_ADDR="127.0.0.1"
    - HTTP_PORT="8080"
    # Drupal PHPUnit test variables.
    - SIMPLETEST_BASE_URL="http://$HOST_ADDR:$HTTP_PORT"
    # Oracle variables.
    - ORACLE_DOWNLOAD_DIR="$HOME/oracle_download"
    - ORACLE_BASEFILE=oracle-xe-11.2.0-1.0.x86_64.rpm.zip
  matrix:
    - DRUDBAL_ENV="mysql"
    - DRUDBAL_ENV="dbal/mysql"
    - DRUDBAL_ENV="dbal/mysqli"
    - DRUDBAL_ENV="sqlite"
    - DRUDBAL_ENV="dbal/sqlite/file"
    - DRUDBAL_ENV="dbal/sqlite/memory"
    - DRUDBAL_ENV="dbal/oci8"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - env: DRUDBAL_ENV="dbal/oci8"

cache:
  directories:
    - $DRUPAL_STAGING_DIR
    - $ORACLE_DOWNLOAD_DIR

before_install:
  # Set variables.
  - |
      if [[ "$DRUDBAL_ENV" == "mysql" ]]; then
        export DBAL_URL="mysql://root:@$HOST_ADDR/drudbal"
        export SIMPLETEST_DB="mysql://root:@$HOST_ADDR/drudbal#drudbal_"

      elif [[ "$DRUDBAL_ENV" == "dbal/mysql" ]]; then
        export DBAL_URL="mysql://root:@$HOST_ADDR/drudbal"
        export SIMPLETEST_DB="dbal://root:@$HOST_ADDR/drudbal?namespace=Drupal%5CDriver%5CDatabase%5Cdbal&dbal_driver=pdo_mysql#drudbal_"

      elif [[ "$DRUDBAL_ENV" == "dbal/mysqli" ]]; then
        export DBAL_URL="mysqli://root:@$HOST_ADDR/drudbal"
        export SIMPLETEST_DB="dbal://root:@$HOST_ADDR/drudbal?namespace=Drupal%5CDriver%5CDatabase%5Cdbal&dbal_driver=mysqli#drudbal_"

      elif [[ "$DRUDBAL_ENV" == "sqlite" ]]; then
        export DBAL_URL="sqlite:///sites/default/files/.ht.sqlite"
        export SIMPLETEST_DB="sqlite://test_user:test_pass@test_host:3306/sites/default/files/.ht.sqlite"

      elif [[ "$DRUDBAL_ENV" == "dbal/sqlite/file" ]]; then
        export DBAL_URL="sqlite:///sites/default/files/.ht.sqlite"
        export SIMPLETEST_DB="dbal://fake/sites/default/files/.ht.sqlite?namespace=Drupal%5CDriver%5CDatabase%5Cdbal&dbal_driver=pdo_sqlite"

      elif [[ "$DRUDBAL_ENV" == "dbal/sqlite/memory" ]]; then
        export DBAL_URL="sqlite:///:memory:"
        export SIMPLETEST_DB="dbal://fake/:memory:?namespace=Drupal%5CDriver%5CDatabase%5Cdbal&dbal_driver=pdo_sqlite"

      elif [[ "$DRUDBAL_ENV" == "dbal/oci8" ]]; then
        export DBAL_URL="oci8://ORAROOT:DRUDBAL@$HOST_ADDR:1521/XE"
        export SIMPLETEST_DB="dbal://ORAROOT:DRUDBAL@$HOST_ADDR:1521/XE?namespace=Drupal%5CDriver%5CDatabase%5Cdbal&dbal_driver=oci8"

      fi

  # Get Oracle XE.
  - |
      if [[ "$DRUDBAL_ENV" == "dbal/oci8" ]]; then
        export ORACLE_COOKIE=sqldev
        export ORACLE_FILE=oracle11g/xe/$ORACLE_BASEFILE
        export ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
        export ORACLE_SID=XE
        wget 'https://github.com/cbandy/travis-oracle/archive/v2.0.2.tar.gz'
        mkdir -p .travis/oracle
        tar x -C .travis/oracle --strip-components=1 -f v2.0.2.tar.gz
        if [[ ! -f $ORACLE_DOWNLOAD_DIR/$ORACLE_BASEFILE ]]; then
          .travis/oracle/download.sh
          cp .travis/oracle/$ORACLE_BASEFILE $ORACLE_DOWNLOAD_DIR
        fi
        if [[ ! -f .travis/oracle/$ORACLE_BASEFILE ]]; then
          cp $ORACLE_DOWNLOAD_DIR/$ORACLE_BASEFILE .travis/oracle/
        fi
        .travis/oracle/install.sh
        chmod 777 $HOME/build/mondrake/drudbal/tests/travis_ci/$DRUDBAL_ENV/oracle_user.sh
        $HOME/build/mondrake/drudbal/tests/travis_ci/$DRUDBAL_ENV/oracle_user.sh
        # Install Oci8 extension for PHP.
        echo $ORACLE_HOME | pecl install oci8

      fi

  # Remove XDebug.
  - phpenv config-rm xdebug.ini
  # Add APCu extension.
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Stage Drupal core to get dependencies.
  - |
      if [[ ! -f $DRUPAL_STAGING_DIR/index.php ]]; then
        git clone http://git.drupal.org/project/drupal.git $DRUPAL_STAGING_DIR
        cd $DRUPAL_STAGING_DIR
        composer install --no-progress --no-suggest
        # Get Drupal Console
        composer require "drupal/console:~1.0.0" --no-progress
        composer require "doctrine/common:^2.7.1" --no-progress
        # Get Doctrine DBAL
        composer require "doctrine/dbal:~2.6.1" --no-progress
        composer update --no-progress --no-progress
      fi

  # Always get latest Drupal core.
  - git clone http://git.drupal.org/project/drupal.git $DRUPAL_PATH
  - cd $DRUPAL_PATH

  # Apply Drupal core patches.
  # [#2605284] Testing framework does not work with contributed database drivers
  - curl https://www.drupal.org/files/issues/simpletest_is_broken_on-2605284-89.patch | git apply
  # [#2867788] Log::findCaller fails to report the correct caller function with non-core drivers.
  - curl https://www.drupal.org/files/issues/2867788-22_0.patch | git apply
  # [#2871374] SelectTest::testVulnerableComment fails when driver overrides Select::__toString
  - curl https://www.drupal.org/files/issues/2871374-2.patch | git apply
  # [#2868273] Missing a test for table TRUNCATE while in transaction
  - curl https://www.drupal.org/files/issues/2868273-9.patch | git apply
  # [#2874499] Test failures when db driver is set to not support transactions
  - curl https://www.drupal.org/files/issues/2874499-7-transaction-enabled.patch | git apply
  # [#2875679] BasicSyntaxTest::testConcatFields fails with contrib driver
  - curl https://www.drupal.org/files/issues/2875679-2.patch | git apply
  # [#2879677] Decouple getting table vs column comments in Schema
  - curl https://www.drupal.org/files/issues/2879677-3.patch | git apply
  # [#2881522] Add a Schema::getPrimaryKeyColumns method to remove database specific logic from test
  - curl https://www.drupal.org/files/issues/2881522-2.patch | git apply

install:
  # Copy the vendor dependencies.
  - mkdir -p $DRUPAL_PATH/vendor
  - cp -r $DRUPAL_STAGING_DIR/vendor/. $DRUPAL_PATH/vendor
  - cp -r $DRUPAL_STAGING_DIR/composer.* $DRUPAL_PATH

  # Copy the repo to the modules/contrib directory.
  - mkdir -p $DRUPAL_PATH/modules/contrib/drudbal
  - cp -r $HOME/build/mondrake/drudbal $DRUPAL_PATH/modules/contrib

  # Create a directory for the driver, and symlink it to the module's one.
  - mkdir -p $DRUPAL_PATH/drivers/lib/Drupal/Driver/Database/
  - cd $DRUPAL_PATH/drivers/lib/Drupal/Driver/Database/
  - ln -s $DRUPAL_PATH/modules/contrib/drudbal/drivers/lib/Drupal/Driver/Database/dbal dbal

  # Patch tests for debugging if necessary.
  - cd $DRUPAL_PATH
  - if [[ -f $DRUPAL_PATH/modules/contrib/drudbal/tests/travis_ci/$DRUDBAL_ENV/test_debug.patch ]]; then git apply -v $DRUPAL_PATH/modules/contrib/drudbal/tests/travis_ci/$DRUDBAL_ENV/test_debug.patch; fi

  # Install Drupal.
  - cp $DRUPAL_PATH/modules/contrib/drudbal/tests/travis_ci/*.php $DRUPAL_PATH/core
  - cd $DRUPAL_PATH/core
  - php install_cli.php

  # Get a webserver running.
  #- drupal --quiet server "$DRUPAL_SERVER_ADDRESS:$DRUPAL_SERVER_HTTP_PORT" &
  #- sleep 4s

  # Post install tasks.
  - if [[ ! "$DRUDBAL_ENV" == "dbal/sqlite/memory" ]]; then drupal site:status; fi
  - php post_install.php

script:
  - cd $DRUPAL_PATH/core
  # Only run selected tests to avoid Travis timeout.
  - ../vendor/bin/phpunit --testsuite kernel --group Database,Cache,Entity,views,field,Field

after_script:
  - cd $DRUPAL_PATH/modules/contrib/drudbal
  - ../../../vendor/bin/phpcs

notifications:
  email: false
