# @file
# .travis.yml - Drupal driver for Doctrine DBAL.

language: php

sudo: false

php:
  - 7
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

env:
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin"
    # Drupal specific variables.
    - DATABASE_NAME="drupal_travis_db"
    - DRUSH_DB="mysql://root:@127.0.0.1/$DATABASE_NAME"
    - SIMPLETEST_DB="dbal://root:@127.0.0.1/$DATABASE_NAME?namespace=Drupal%5CDriver%5CDatabase%5Cdbal&dbal_driver=pdo_mysql#travis_"
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"

mysql:
  database: $DATABASE_NAME
  username: root
  encoding: utf8

before_install:
  # Remove XDebug
  - phpenv config-rm xdebug.ini
  # Add APCu extension.
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Get Drupal core and dependencies
  - git clone http://git.drupal.org/project/drupal.git $HOME/drupal8
  - cd $HOME/drupal8
  - composer install

  # Apply Drupal core patches
  # [#2605284] Testing framework does not work with contributed database drivers
  - curl https://www.drupal.org/files/issues/simpletest_is_broken_on-2605284-89.patch | git apply
  # [#2867700] ConnectionUnitTest::testConnectionOpen fails if the driver is not implementing a PDO connection
  - curl https://www.drupal.org/files/issues/2867700-2.patch | git apply
  # [#2867788] Log::findCaller fails to report the correct caller function with non-core drivers.
  - curl https://www.drupal.org/files/issues/2867788-12.patch | git apply
  # [#2871374] SelectTest::testVulnerableComment fails when driver overrides Select::__toString
  - curl https://www.drupal.org/files/issues/2871374-2.patch | git apply

  # Get Drupal Console
  - composer require "drupal/console:~1.0" --prefer-dist --optimize-autoloader

  # Get Doctrine DBAL
  - composer require "doctrine/dbal:^2.5.12"

install:
  # Copy the repo to the modules/contrib directory.
  - mkdir -p $HOME/drupal8/modules/contrib/drudbal
  - cp -r $HOME/build/mondrake/drudbal $HOME/drupal8/modules/contrib

  # Create a directory for the driver, and symlink it to the module's one.
  - mkdir -p $HOME/drupal8/drivers/lib/Drupal/Driver/Database/
  - cd $HOME/drupal8/drivers/lib/Drupal/Driver/Database/
  - ln -s $HOME/drupal8/modules/contrib/drudbal/drivers/lib/Drupal/Driver/Database/dbal dbal

  # Get a live database
  - mysql -e 'CREATE DATABASE $DATABASE_NAME;'

  # Install Drupal
  - cd $HOME/drupal8/core
  - cp $HOME/drupal8/modules/contrib/drudbal/misc/install_cli.php install_cli.php
  - php install_cli.php

  # Get a webserver running.
  - cd $HOME/drupal8/core
  - ../vendor/bin/drupal server "127.0.0.1:8080"
  #- drush --debug runserver $SIMPLETEST_BASE_URL > ~/debug.txt 2>&1 &
  - sleep 4s

script:
  - cd $HOME/drupal8/core
  - ../vendor/bin/phpunit --group xDatabase,Cache,xConfig,xEntity --verbose

notifications:
  email: false
