name: PHPUnit Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: "mysql:5.7"
        options: >-
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes
          -e MYSQL_DATABASE=drudbal
        ports:
          - "3306:3306"

    steps:
    - name: Install PHP
      uses: "shivammathur/setup-php@v2"
      with:
        coverage: "none"
        extensions: "mysqli,pdo_mysql"

    - name: Checkout Drupal
      run: git clone --depth=5 --branch=9.2.x http://git.drupal.org/project/drupal.git .

    - name: Checkout DruDbal
      uses: actions/checkout@v2
      with:
        path: dbal_staging

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: |
        #cd drupal
        composer install --no-progress
        composer run-script drupal-phpunit-upgrade
        composer require drush/drush --no-progress

    - name: Install Drupal
      run: |
        #cd drupal
        vendor/bin/drush site-install standard --db-url="mysql://root:@0.0.0.0:3306/drudbal#drudbal_" -y
        vendor/bin/drush runserver localhost:8080 &
        sleep 2s

    - name: Run test suite
      run: |
        #cd drupal/core
        export SIMPLETEST_BASE_URL="http://localhost:8080"
        export SIMPLETEST_DB="mysql://root:@0.0.0.0:3306/drudbal#drudbal_"
        vendor/bin/phpunit --group Database
